version: '3'
services:
  api: 
    build: ./api
    container_name: api_c
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - /opt/dockerdeployment/api:/app
      - /app/node_modules
  myblog:
    build: ./myblog
    container_name: myblog_c
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./myblog/default.conf:/etc/nginx/conf.d/default.conf/:ro
      - ./certbot/www:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw