version: '3'
services:
  api: 
    build: ./api
    container_name: api
    restart: always
    ports:
      - '8001:8001'
    volumes:
      - './api:/app'
      - /app/node_modules
  myblog:
    build: ./myblog
    container_name: myblog
    restart: always
    ports:
      - '80:3000'
    stdin_open: true
    tty: true