version: '3'
services:
  api: 
    build: ./api
    container_name: api
    restart: always
    ports:
      - '8001:8001'
    volumes:
      - '/opt/dockerdeployment/api:/app'
      - /app/node_modules
  myblog:
    build: ./myblog
    container_name: myblog
    restart: always
    ports:
      - '80:3000'
    volumes:
      - '/opt/dockerdeployment/myblog:/app'
      - /app/node_modules
      - /host/nginx/sites-available/default:/etc/nginx/sites-available/default