version: '3'
services:
  api: 
    build: ./api
    container_name: api
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - /opt/dockerdeployment/api:/app
      - /app/node_modules
      - ./deploy/api/default.conf:/etc/nginx/sites-available/default
  myblog:
    build: ./myblog
    container_name: myblog
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /opt/dockerdeployment/myblog:/app
      - /app/node_modules
      - ./deploy/myblog/default.conf:/etc/nginx/sites-available/default