version: '3'
services:
  api: 
    build: ./api
    container_name: api_c
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - /opt/dockerdeployment/api:/app
      - /app/node_modules
  myblog:
    build: ./myblog
    container_name: myblog_c
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /opt/dockerdeployment/myblog:/app
      - /app/node_modules
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro